AllCops:
  NewCops: enable
Style/SymbolArray:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Max: 30
  IgnoredMethods: ["describe", "context", "feature", "scenario"]
  Exclude:
    - "spec/**/*.rb"
    - "config/routes/*.rb"
    - "engines/member_api/config/routes.rb"
    - "engines/admin_api/config/routes.rb"
